import { VendorOrderStatusEnum } from "./orders.enums";

export const ORDER_CACHE_TTL = 300;
export const RAZORPAY_HEADER_SIGNATURE_KEY = "x-razorpay-signature";

export const ERROR_MESSAGES = {
  ORDER_NOT_FOUND: "Order not found",
  ORDER_NOT_BELONG_TO_USER: "Order does not belong to current user",
  ADDRESS_NOT_FOUND: "Address not found",
  ADDRESS_NOT_BELONG_TO_USER: "Address does not belong to current user",
  CART_NOT_FOUND: "Cart not found",
  CART_EMPTY: "Cart is empty",
  PRODUCT_NOT_FOUND: "Product not found",
  PRODUCT_NOT_APPROVED: "Product is not approved",
  PRODUCT_INACTIVE: "Product is not active",
  VENDOR_NOT_APPROVED: "Vendor is not approved",
  INSUFFICIENT_STOCK: "Insufficient stock for product",
  ORDER_ALREADY_PAID: "Order is already paid",
  INVALID_ORDER_STATUS: "Invalid order status for this operation",
  WEBHOOK_SIGNATURE_INVALID: "Invalid webhook signature",
  WEBHOOK_AMOUNT_MISMATCH: "Webhook amount does not match order amount",
  WEBHOOK_SECRET_MISSING: "Webhook secret not configured",
  VENDOR_ORDER_MAPPING_FAILED: "Vendor order mapping failed",
  ORDER_CONTAINS_NO_ITEMS: "Order contains no items",
  ORDER_STATUS_ALREADY_SET: "Order status is already set.",
  ORDER_PAYMENT_PENDING: "Order can't be updated because payment is pending",
  INVALID_SORT_FIELD: "Invalid sort field for order listing",
  INVALID_VENDOR_ORDER_STATUS_TRANSITION: (currentStatus: string, nextStatus: string) =>
    `Invalid vendor status transition from ${currentStatus} to ${nextStatus}`,
  ORDER_CANNOT_BE_CANCELLED: "Order cannot be cancelled",
  ORDER_ALREADY_CANCELLED: "Order is already cancelled",
  VENDOR_ORDER_NOT_CANCELLABLE: "One or more vendor orders cannot be cancelled",
};

export const VALID_VENDOR_ORDER_STATUS_TRANSITION: Record<VendorOrderStatusEnum, VendorOrderStatusEnum[]> = {
  // Pending -> processing or Rejected
  [VendorOrderStatusEnum.PENDING]: [VendorOrderStatusEnum.CANCELLED, VendorOrderStatusEnum.PROCESSING],

  // processing -> cancelled, shipped
  [VendorOrderStatusEnum.PROCESSING]: [VendorOrderStatusEnum.CANCELLED, VendorOrderStatusEnum.SHIPPED],

  // shipped -> delivered
  [VendorOrderStatusEnum.SHIPPED]: [VendorOrderStatusEnum.DELIVERED],

  // delivered ->  Can't update status
  [VendorOrderStatusEnum.DELIVERED]: [],

  // cancelled ->  Can't update status
  [VendorOrderStatusEnum.CANCELLED]: [],
};

export const SUCCESS_MESSAGES = {
  CHECKOUT_SUCCESS: "Order created successfully",
  PAYMENT_INITIATED: "Payment initiated successfully",
  ORDER_CONFIRMED: "Order confirmed successfully",
  ORDER_CANCELLED: "Order cancelled successfully",
  WEBHOOK_PROCESSED: "Webhook processed successfully",
  ORDER_STATUS_UPDATED: "Order Status Updated Successfully.",
};

export const ORDER_SELECT_FIELDS = {
  CART_ITEM: [
    "cartItems.id",
    "cartItems.cartId",
    "cartItems.productId",
    "cartItems.quantity",
    "cartItems.priceSnapshot",
    "cartItems.discountPriceSnapshot",
    "cartItems.slugSnapshot",
    "cartItems.nameSnapshot",
  ],
  ORDER: [
    "order.id",
    "order.userId",
    "order.addressId",
    "order.orderNumber",
    "order.totalAmount",
    "order.paymentMethod",
    "order.paymentStatus",
    "order.razorpayOrderId",
    "order.razorpayPaymentId",
    "order.status",
    "order.placedAt",
    "order.createdAt",
    "order.updatedAt",
  ],
  ORDER_FOR_USER: [
    "order.id",
    "order.userId",
    "order.addressId",
    "order.orderNumber",
    "order.totalAmount",
    "order.paymentMethod",
    "order.paymentStatus",
    "order.razorpayOrderId",
    "order.razorpayPaymentId",
    "order.status",
    "order.placedAt",
    "order.createdAt",
    "order.updatedAt",
    "address.fullName",
    "address.phoneNumber",
    "address.addressLine1",
    "address.addressLine2",
    "address.city",
    "address.state",
    "address.country",
    "address.postalCode",
  ],
  ORDER_FOR_USER_DETAILS: [
    "order.id",
    "order.userId",
    "order.orderNumber",
    "order.totalAmount",
    "order.paymentMethod",
    "order.paymentStatus",
    "order.status",
    "order.placedAt",
    "address.fullName",
    "address.phoneNumber",
    "address.addressLine1",
    "address.addressLine2",
    "address.city",
    "address.state",
    "address.country",
    "address.postalCode",
  ],
  ORDER_FOR_ADMIN_DETAILS: [
    "order.id",
    "order.userId",
    "order.orderNumber",
    "order.totalAmount",
    "order.paymentMethod",
    "order.paymentStatus",
    "order.razorpayOrderId",
    "order.razorpayPaymentId",
    "order.status",
    "order.placedAt",
    "address.fullName",
    "address.phoneNumber",
    "address.addressLine1",
    "address.addressLine2",
    "address.city",
    "address.state",
    "address.country",
    "address.postalCode",
  ],
  ORDER_USER_FOR_ADMIN_DETAILS: ["user.id", "user.firstName", "user.lastName", "user.email", "user.phoneNumber"],
  ORDER_FOR_PAYMENT: [
    "order.id",
    "order.userId",
    "order.orderNumber",
    "order.totalAmount",
    "order.paymentMethod",
    "order.paymentStatus",
    "order.razorpayOrderId",
    "order.razorpayPaymentId",
    "order.status",
  ],
  ORDER_FOR_WEBHOOK: [
    "order.id",
    "order.userId",
    "order.orderNumber",
    "order.totalAmount",
    "order.paymentMethod",
    "order.paymentStatus",
    "order.razorpayOrderId",
    "order.razorpayPaymentId",
    "order.status",
  ],
  VENDOR_ORDER: [
    "vendorOrder.id",
    "vendorOrder.orderId",
    "vendorOrder.vendorId",
    "vendorOrder.totalAmount",
    "vendorOrder.status",
    "vendorOrder.createdAt",
  ],
  VENDOR_ORDER_FOR_DETAILS: [
    "vendorOrder.id",
    "vendorOrder.orderId",
    "vendorOrder.vendorId",
    "vendorOrder.totalAmount",
    "vendorOrder.status",
    "vendor.businessName",
  ],
  ORDER_ITEM: [
    "orderItem.id",
    "orderItem.vendorOrderId",
    "orderItem.productId",
    "orderItem.quantity",
    "orderItem.unitPrice",
    "orderItem.totalPrice",
    "orderItem.skuSnapshot",
    "orderItem.nameSnapshot",
    "orderItem.slugSnapshot",
  ],
  ORDER_ITEM_FOR_DETAILS: [
    "orderItem.id",
    "orderItem.productId",
    "orderItem.quantity",
    "orderItem.unitPrice",
    "orderItem.totalPrice",
    "orderItem.skuSnapshot",
    "orderItem.nameSnapshot",
    "orderItem.slugSnapshot",
    "orderItem.vendorOrderId",
  ],
  PRODUCT: [
    "product.id",
    "product.vendorId",
    "product.name",
    "product.slug",
    "product.sku",
    "product.price",
    "product.discountPrice",
    "product.stock",
  ],
  VENDOR_ORDER_ID: ["vendorOrder.id"],
  ORDER_INFO: ["orderItem.id, orderItem.productId", "orderItem.quantity"],
  PRODUCT_INFO: ["product.id", "product.stock", "product.status", "product.isActive"],
};

export const PAYMENT_CURRENCY = {
  INR: "INR",
};

export const ORDER_ERROR_CONTEXT = {
  CHECKOUT: "Checkout",
  INITIATE_PAYMENT: "Initiate Payment",
  PROCESS_WEBHOOK: "Process Webhook",
  STOCK_DECREMENT: "Stock Decrement",
  REFUND_PAYMENT: "Refund Payment",
  UPDATE_ORDER_STATUS: "Update Order Status",
  CANCEL_ORDER: "Cancel Order",
};

export const PAYMENT_STATUS_RAZORPAY = {
  CAPTURED: "payment.captured",
  FAILED: "payment.failed",
};
