allowBuilds:
  '@nestjs/core': false
  '@scarf/scarf': false
  '@swc/core': false
  core-js: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1049.0'
  - '@aws-sdk/client-ses@3.1049.0'
  - '@aws-sdk/core@3.974.12'
  - '@aws-sdk/credential-provider-env@3.972.38'
  - '@aws-sdk/credential-provider-http@3.972.40'
  - '@aws-sdk/credential-provider-ini@3.972.42'
  - '@aws-sdk/credential-provider-login@3.972.42'
  - '@aws-sdk/credential-provider-node@3.972.43'
  - '@aws-sdk/credential-provider-process@3.972.38'
  - '@aws-sdk/credential-provider-sso@3.972.42'
  - '@aws-sdk/credential-provider-web-identity@3.972.42'
  - '@aws-sdk/middleware-bucket-endpoint@3.972.14'
  - '@aws-sdk/middleware-flexible-checksums@3.974.20'
  - '@aws-sdk/middleware-sdk-s3@3.972.41'
  - '@aws-sdk/nested-clients@3.997.10'
  - '@aws-sdk/s3-presigned-post@3.1049.0'
  - '@aws-sdk/s3-request-presigner@3.1049.0'
  - '@aws-sdk/token-providers@3.1049.0'
  - '@typescript-eslint/parser@8.59.4'
  - '@typescript-eslint/project-service@8.59.4'
  - '@typescript-eslint/scope-manager@8.59.4'
  - '@typescript-eslint/tsconfig-utils@8.59.4'
  - '@typescript-eslint/types@8.59.4'
  - '@typescript-eslint/typescript-estree@8.59.4'
  - '@typescript-eslint/visitor-keys@8.59.4'
  - pg-cloudflare@1.4.0
  - pg-connection-string@2.13.0
  - pg-pool@3.14.0
  - pg-protocol@1.14.0
  - pg@8.21.0
  - typeorm@0.3.30
