export enum ApiTag {
  Users = "Users",
  Orders = "Orders",
  Stripe = "Stripe",
  Subscriptions = "Subscriptions",
  Prices = "Prices",
  Plans = "Plans",
  Role = "Role",
  Transactions = "Transactions",
  Auth = "Auth",
  Multipart = "Multipart",
  Presigned = "Presigned",
  Download = "Download",
  Vendors = "Vendors",
  Categories = "Categories",
  Products = "Products",
  Media = "Media",
  Carts = "Carts",
  Webhook = "Webhook",
  Analytics = "Analytics",
  Reviews = "Reviews",
}
